travis:
  secure:
    BINSTAR_TOKEN: AfLjQy9e3jQ5mkLItb9iVR5dth1hyE523tVluvpEWuLVe0oudvkLmsXKC/kpquUSQ9HALcG1E6X5ZRQc+uyarRcEDvaa3iAjcKL1k1WFVTcsR/Q9W5of3e8S/42rCz7y0NULJ6oRjeTE+qcDBgM9J5UEz5i/dPDGI2HuWVBkuk7MBRCsSUXi7Ygh8lAOpHYz0oAD6JNqltwmCkSQQaO75GHnQQXYGmLdKV27jCII9JSTbuzuhG7IWZ/2f3OnNldf9ErcFRvnOpo82qElcPRNnpkxVC1PRV1tPzgX8ttx23xuQp9Q1GGoGVnbnHCDmSB41/8GLC06Ci40AxODWTiClp2g9SxkoVJfJ9Wrem2IINWRyMjNS9CeK8PQtaV22bDknYAWwzv69+3lf6KtDG1sMVTXgU5lBSf+8aIdRR6Lf9o4ErmuEZzKqzSD2/2hzYBOQwjNHMgmM8uhB6Jyr6JE6Wr2gkbs1etsvkSqJI75R3Sxm+jxIZo844nQmDd+hgPVjijP/MMXcdKCceAgKEN/kaVNbZkPTMUQJCx6xdK1044op11BzXRC5adK2ARuEqYKMqutknRycnHGcP3QLag8pSaPgjPiX9+RhZqt5HniiWqE6NEbuEL2ENoQSp3h3VV/wHpDeVgaKzcl+TmH2QjZrhWSn+6Li/NJgZR+oqh/Vm4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
